name: API ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  read-from-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: set python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: get data from API
        env:
          API_TOKEN: ${{secrets.API_TOKEN}}
        run: python read_data_api.py
